#!/bin/bash

# make bash behave
set -euxo pipefail
IFS=$'\n\t'

# this script needs root to install packages
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

cd / && tar xfv "${CIRCLE_WORKING_DIRECTORY}/install-${PG_MAJOR}.tar"

status=0

gosu circleci bash <<EOF
ulimit -c unlimited
make -C "${CIRCLE_WORKING_DIRECTORY}/build-${PG_MAJOR}/src/test/regress" "${@}" || status=$?

cd "${CIRCLE_WORKING_DIRECTORY}/build-${PG_MAJOR}/src/test/regress"
PROJECT_ROOT="${CIRCLE_WORKING_DIRECTORY}" generate-test-reports regress

exit $status
EOF
